/**
 * SmartGov AI – Kakinada
 * DEMO DATA MODULE
 * 
 * This module provides in-memory mock data when no database is connected.
 * Perfect for demos and local development without PostgreSQL.
 */

const OFFICES = [
  { id: 'a1-meeseva', name: 'MeeSeva', type: 'government', city: 'Kakinada', address: 'MeeSeva Center, Main Road, Kakinada, AP 533001', phone: '0884-2301234', google_map_url: 'https://maps.google.com/?q=MeeSeva+Kakinada', is_active: true, working_hours: { monday:'09:00-17:00',tuesday:'09:00-17:00',wednesday:'09:00-17:00',thursday:'09:00-17:00',friday:'09:00-17:00',saturday:'09:00-13:00',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'a2-rto', name: 'RTO Office', type: 'government', city: 'Kakinada', address: 'Regional Transport Office, Auto Nagar, Kakinada, AP 533003', phone: '0884-2302345', google_map_url: 'https://maps.google.com/?q=RTO+Kakinada', is_active: true, working_hours: { monday:'10:00-17:00',tuesday:'10:00-17:00',wednesday:'10:00-17:00',thursday:'10:00-17:00',friday:'10:00-17:00',saturday:'10:00-13:00',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'a3-collectorate', name: 'Collectorate', type: 'government', city: 'Kakinada', address: 'District Collectorate, Collectorate Road, Kakinada, AP 533001', phone: '0884-2303456', google_map_url: 'https://maps.google.com/?q=Collectorate+Kakinada', is_active: true, working_hours: { monday:'10:30-17:00',tuesday:'10:30-17:00',wednesday:'10:30-17:00',thursday:'10:30-17:00',friday:'10:30-17:00',saturday:'closed',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'a4-municipal', name: 'Municipal Corporation', type: 'government', city: 'Kakinada', address: 'GVMC Office, Softy Center, Kakinada, AP 533001', phone: '0884-2304567', google_map_url: 'https://maps.google.com/?q=Municipal+Corporation+Kakinada', is_active: true, working_hours: { monday:'10:00-17:00',tuesday:'10:00-17:00',wednesday:'10:00-17:00',thursday:'10:00-17:00',friday:'10:00-17:00',saturday:'10:00-13:00',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'a5-registration', name: 'Registration Office', type: 'government', city: 'Kakinada', address: 'Sub-Registrar Office, Court Road, Kakinada, AP 533001', phone: '0884-2305678', google_map_url: 'https://maps.google.com/?q=Registration+Office+Kakinada', is_active: true, working_hours: { monday:'10:00-16:00',tuesday:'10:00-16:00',wednesday:'10:00-16:00',thursday:'10:00-16:00',friday:'10:00-16:00',saturday:'closed',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'a6-tahsildar', name: 'Tahsildar Office', type: 'government', city: 'Kakinada', address: 'Tahsildar Office, Bommuru Road, Kakinada, AP 533002', phone: '0884-2306789', google_map_url: 'https://maps.google.com/?q=Tahsildar+Office+Kakinada', is_active: true, working_hours: { monday:'10:00-17:00',tuesday:'10:00-17:00',wednesday:'10:00-17:00',thursday:'10:00-17:00',friday:'10:00-17:00',saturday:'10:00-13:00',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'a7-passport', name: 'Passport Office', type: 'government', city: 'Kakinada', address: 'Passport Seva Kendra, Beside Collectorate, Kakinada, AP 533001', phone: '0884-2307890', google_map_url: 'https://maps.google.com/?q=Passport+Office+Kakinada', is_active: true, working_hours: { monday:'09:00-17:00',tuesday:'09:00-17:00',wednesday:'09:00-17:00',thursday:'09:00-17:00',friday:'09:00-17:00',saturday:'closed',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'b1-sbi', name: 'SBI', type: 'bank', city: 'Kakinada', address: 'State Bank of India, Main Branch, Bander Road, Kakinada, AP 533001', phone: '0884-2320001', google_map_url: 'https://maps.google.com/?q=SBI+Kakinada+Main+Branch', is_active: true, working_hours: { monday:'10:00-16:00',tuesday:'10:00-16:00',wednesday:'10:00-16:00',thursday:'10:00-16:00',friday:'10:00-16:00',saturday:'10:00-13:00',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'b2-union', name: 'Union Bank', type: 'bank', city: 'Kakinada', address: 'Union Bank of India, Jagannaickpur, Kakinada, AP 533005', phone: '0884-2320002', google_map_url: 'https://maps.google.com/?q=Union+Bank+Kakinada', is_active: true, working_hours: { monday:'10:00-16:00',tuesday:'10:00-16:00',wednesday:'10:00-16:00',thursday:'10:00-16:00',friday:'10:00-16:00',saturday:'10:00-13:00',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'b3-canara', name: 'Canara Bank', type: 'bank', city: 'Kakinada', address: 'Canara Bank, Main Road, Kakinada, AP 533001', phone: '0884-2320003', google_map_url: 'https://maps.google.com/?q=Canara+Bank+Kakinada', is_active: true, working_hours: { monday:'10:00-16:00',tuesday:'10:00-16:00',wednesday:'10:00-16:00',thursday:'10:00-16:00',friday:'10:00-16:00',saturday:'10:00-13:00',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'b4-indian', name: 'Indian Bank', type: 'bank', city: 'Kakinada', address: 'Indian Bank, Suryaraopeta, Kakinada, AP 533002', phone: '0884-2320004', google_map_url: 'https://maps.google.com/?q=Indian+Bank+Kakinada', is_active: true, working_hours: { monday:'10:00-16:00',tuesday:'10:00-16:00',wednesday:'10:00-16:00',thursday:'10:00-16:00',friday:'10:00-16:00',saturday:'10:00-13:00',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'b5-andhra', name: 'Andhra Bank', type: 'bank', city: 'Kakinada', address: 'Andhra Bank, Softy Centre, Kakinada, AP 533001', phone: '0884-2320005', google_map_url: 'https://maps.google.com/?q=Andhra+Bank+Kakinada', is_active: true, working_hours: { monday:'10:00-16:00',tuesday:'10:00-16:00',wednesday:'10:00-16:00',thursday:'10:00-16:00',friday:'10:00-16:00',saturday:'10:00-13:00',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'b6-hdfc', name: 'HDFC Bank', type: 'bank', city: 'Kakinada', address: 'HDFC Bank, Bander Road, Kakinada, AP 533001', phone: '0884-2320006', google_map_url: 'https://maps.google.com/?q=HDFC+Bank+Kakinada', is_active: true, working_hours: { monday:'10:00-16:00',tuesday:'10:00-16:00',wednesday:'10:00-16:00',thursday:'10:00-16:00',friday:'10:00-16:00',saturday:'10:00-13:00',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'b7-icici', name: 'ICICI Bank', type: 'bank', city: 'Kakinada', address: 'ICICI Bank, Main Road, Kakinada, AP 533001', phone: '0884-2320007', google_map_url: 'https://maps.google.com/?q=ICICI+Bank+Kakinada', is_active: true, working_hours: { monday:'10:00-16:00',tuesday:'10:00-16:00',wednesday:'10:00-16:00',thursday:'10:00-16:00',friday:'10:00-16:00',saturday:'10:00-13:00',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
  { id: 'b8-axis', name: 'Axis Bank', type: 'bank', city: 'Kakinada', address: 'Axis Bank, Ramaraopeta, Kakinada, AP 533004', phone: '0884-2320008', google_map_url: 'https://maps.google.com/?q=Axis+Bank+Kakinada', is_active: true, working_hours: { monday:'10:00-16:00',tuesday:'10:00-16:00',wednesday:'10:00-16:00',thursday:'10:00-16:00',friday:'10:00-16:00',saturday:'10:00-13:00',sunday:'closed' }, lunch_break: { start:'13:00',end:'14:00' } },
];

const SERVICES = {
  'a1-meeseva': [
    { id: 's1', office_id: 'a1-meeseva', name: 'Income Certificate', category: 'Certificates', fees: 30, fees_description: '₹30 service charge', eligibility: 'Any resident of Andhra Pradesh', processing_time: '3-7 working days', documents_required: ['Aadhaar Card','Ration Card','Salary Slip or Income Proof','Residence Proof','Passport Size Photo','Application Form'], steps: ['Visit MeeSeva center and take a token','Submit application form with documents','Pay ₹30 service fee','Receive acknowledgment slip','Collect certificate after 3-7 days or download online'], faqs: [{q:'Can I apply online?',a:'Yes, through meeseva.ap.gov.in'},{q:'How long is valid?',a:'1 year'}] },
    { id: 's2', office_id: 'a1-meeseva', name: 'Caste Certificate', category: 'Certificates', fees: 30, fees_description: '₹30 service charge', eligibility: 'SC/ST/OBC communities', processing_time: '7-15 working days', documents_required: ['Aadhaar Card','Ration Card','Parent Caste Certificate','School Transfer Certificate','Passport Size Photo'], steps: ['Get application form from MeeSeva','Fill and attach documents','Submit and pay ₹30','Tahsildar verification may be required','Collect after verification'], faqs: [{q:'Valid across states?',a:'Valid within AP only'}] },
    { id: 's3', office_id: 'a1-meeseva', name: 'Residence Certificate', category: 'Certificates', fees: 30, fees_description: '₹30 service charge', eligibility: 'AP residents with 6+ months residence', processing_time: '3-5 working days', documents_required: ['Aadhaar Card','Ration Card','Electricity Bill or Water Bill','Rental Agreement (if rented)'], steps: ['Visit MeeSeva with originals','Submit application and pay fee','Field verification may be done','Collect after 3-5 days'], faqs: [{q:'Is Aadhaar alone sufficient?',a:'Aadhaar + one supporting doc required'}] },
    { id: 's4', office_id: 'a1-meeseva', name: 'Birth Certificate', category: 'Certificates', fees: 50, fees_description: '₹50 per copy', eligibility: 'Parents of child born in AP', processing_time: '1-3 working days', documents_required: ['Hospital Discharge Summary','Parents Aadhaar','Marriage Certificate','Application Form'], steps: ['Apply within 21 days of birth (free)','After 21 days visit Municipal Corp','Submit hospital papers','Pay fee and collect'], faqs: [{q:'What if not registered?',a:'Apply through Tahsildar with affidavit'}] },
    { id: 's5', office_id: 'a1-meeseva', name: 'Death Certificate', category: 'Certificates', fees: 50, fees_description: '₹50 per copy', eligibility: 'Family or legal heirs of deceased', processing_time: '1-3 working days', documents_required: ['Hospital/Doctor Death Certificate','Deceased Aadhaar','Applicant Aadhaar'], steps: ['Register death within 21 days','Submit hospital certificate','Pay fee and collect'], faqs: [{q:'Death at home?',a:'Submit declaration from ward/panchayat head'}] },
    { id: 's5b', office_id: 'a1-meeseva', name: 'Encumbrance Certificate (EC)', category: 'Land Records', fees: 200, fees_description: '₹200 for 30 year search', eligibility: 'Property owners / Buyers in AP', processing_time: '1-2 working days', documents_required: ['Property Survey Number','Sale Deed Copy','Applicant Aadhaar Card'], steps: ['Submit property details at MeeSeva counter','Pay search fee of ₹200','EC generated and stamped by Sub-Registrar','Collect physical copy or download PDF'], faqs: [{q:'What period is covered?',a:'Up to 30 years search report'}] },
  ],

  'a2-rto': [
    { id: 's6', office_id: 'a2-rto', name: 'Driving Licence – Fresh', category: 'Licence', fees: 400, fees_description: 'LL ₹200 + DL ₹200', eligibility: 'Age 18+ (four-wheelers), 16+ (two-wheelers)', processing_time: '30-60 days', documents_required: ['Aadhaar Card','DOB Proof','Address Proof','Photos (6)','Medical Certificate (Form 1A)'], steps: ['Apply for Learning Licence online','Appear for LL written test','Practice 30 days','Book Driving Test slot','Appear for test at RTO','Collect DL after 7-10 days'], faqs: [{q:'Can I apply online?',a:'Yes at parivahan.gov.in'},{q:'How many attempts?',a:'3 attempts in 6 months'}] },
    { id: 's7', office_id: 'a2-rto', name: 'Driving Licence – Renewal', category: 'Licence', fees: 200, fees_description: 'Renewal fee ₹200', eligibility: 'Expired or near-expiry DL holders', processing_time: '7-15 days', documents_required: ['Existing DL (original)','Aadhaar Card','Medical Certificate (40+ age)','Photos (2)'], steps: ['Apply online or visit RTO','Submit form and pay','Medical test if 40+','New DL dispatched by post'], faqs: [{q:'Can I renew expired DL?',a:'Yes up to 5 years after expiry'}] },
    { id: 's8', office_id: 'a2-rto', name: 'Vehicle Registration (RC)', category: 'Registration', fees: 1500, fees_description: 'Varies by vehicle class', eligibility: 'New vehicle buyers', processing_time: '1-3 working days', documents_required: ['Sale Certificate (Form 21)','Road Worthiness Certificate','Insurance Policy','Aadhaar Card','PAN Card'], steps: ['Dealer uploads documents','RTO inspection if required','Pay road tax and registration fee','Smart card RC mailed to home'], faqs: [{q:'Temporary registration valid for?',a:'30 days'}] },
    { id: 's8b', office_id: 'a2-rto', name: 'Ownership Transfer (RC Transfer)', category: 'Registration', fees: 500, fees_description: 'Transfer fee ₹500', eligibility: 'Vehicle buyers & sellers', processing_time: '7-14 working days', documents_required: ['Original RC','Form 29 & Form 30','Valid Insurance','Pollution (PUC) Certificate','Buyer & Seller Aadhaar'], steps: ['Submit Form 29 & 30 signed by both parties','Pay transfer fee','RTO verifies documents','Updated RC issued to new owner'], faqs: [{q:'NOC required for intra-state transfer?',a:'No, NOC only needed for inter-state transfer'}] },
  ],

  'a3-collectorate': [
    { id: 's9a', office_id: 'a3-collectorate', name: 'Public Grievance Submission (Spandana)', category: 'Public Services', fees: 0, fees_description: 'Free Govt Service', eligibility: 'Any citizen of East Godavari District', processing_time: '7-14 working days', documents_required: ['Aadhaar Card','Grievance Petition Letter','Supporting Proof Documents'], steps: ['Submit petition at Collectorate Spandana counter or online','Receive Grievance Tracking Number','Department officer reviews complaint','Resolution report sent to citizen via SMS'], faqs: [{q:'How to track status?',a:'Track using petition number on Spandana portal'}] },
    { id: 's9b', office_id: 'a3-collectorate', name: 'Pension Inquiry & Registration', category: 'Welfare', fees: 0, fees_description: 'Free Govt Scheme', eligibility: 'Senior Citizens (60+), Widows, Disabled persons', processing_time: '15-30 working days', documents_required: ['Aadhaar Card','Rice Card / Ration Card','Age Proof Certificate','Bank Passbook Copy','Disability Certificate (if applicable)'], steps: ['Submit application form at Collectorate welfare counter','Gram/Ward Sachivalayam verification','District Collector sanction','Monthly pension credited to bank account'], faqs: [{q:'Monthly pension amount?',a:'₹3,000 per month for YSR/AP Pension Scheme'}] },
  ],

  'a4-municipal': [
    { id: 's10a', office_id: 'a4-municipal', name: 'Property Tax Payment & Assessment', category: 'Taxes', fees: 0, fees_description: 'Tax based on property area', eligibility: 'Property owners in Kakinada Municipal limit', processing_time: 'Instant receipt', documents_required: ['Property Assessment Number','Previous Tax Receipt','Aadhaar Card'], steps: ['Visit Municipal office counter or online portal','Enter Assessment Number','Pay via Cash, UPI, or Card','Collect official computer-generated receipt'], faqs: [{q:'Rebate for early payment?',a:'5% rebate if paid in April month'}] },
    { id: 's10b', office_id: 'a4-municipal', name: 'New Water Connection Application', category: 'Utilities', fees: 500, fees_description: 'Connection fee ₹500 + meter cost', eligibility: 'House owners in Kakinada Corporation limits', processing_time: '7-10 working days', documents_required: ['Property Tax Receipt','Ownership Proof','Aadhaar Card','House Plan Copy'], steps: ['Submit application form with property documents','Municipal engineer site inspection','Pay tap connection connection charges','Pipeline laying and meter installation'], faqs: [{q:'Can commercial buildings apply?',a:'Yes, separate tariff applies'}] },
    { id: 's10c', office_id: 'a4-municipal', name: 'Trade Licence Application', category: 'Licences', fees: 1000, fees_description: '₹1000 - ₹5000 based on business area', eligibility: 'Business owners operating in Kakinada', processing_time: '5-7 working days', documents_required: ['Rental Agreement / Property Proof','PAN Card','Aadhaar Card','NOC from Fire/Health Dept (if required)'], steps: ['Apply at Municipal Trade Licence counter','Sanitary inspector premises inspection','Pay prescribed licence fee','Trade licence certificate issued'], faqs: [{q:'Validity period?',a:'Valid for 1 financial year (Renew annually by March 31)'}] },
  ],

  'a5-registration': [
    { id: 's11a', office_id: 'a5-registration', name: 'Property Sale Deed Registration', category: 'Registration', fees: 1000, fees_description: 'Registration fee 1% + Stamp Duty 5%', eligibility: 'Property Buyers & Sellers', processing_time: 'Same day (2-4 hours)', documents_required: ['Draft Sale Deed','Encumbrance Certificate (EC)','Link Documents (13 yrs)','Buyer & Seller Aadhaar & PAN','Two Witnesses with Aadhaar'], steps: ['Book online slot at Sub-Registrar office','Pay stamp duty and registration fees online','Present before Sub-Registrar with witnesses','Biometric fingerprint scan & photo capture','Registered document handed over'], faqs: [{q:'Is PAN card mandatory?',a:'Yes for property values above ₹5 Lakhs'}] },
    { id: 's11b', office_id: 'a5-registration', name: 'Marriage Registration', category: 'Registration', fees: 500, fees_description: 'Registration fee ₹500', eligibility: 'Bride (18+) & Groom (21+)', processing_time: '1-3 working days', documents_required: ['Marriage Invitation Card / Photos','Bride & Groom Aadhaar & DOB Proof','Three Witnesses with Aadhaar','Wedding Hall Receipt / Temple Certificate'], steps: ['Submit application to Sub-Registrar','Notice period / Verification','Appear before Registrar with 3 witnesses','Sign marriage register','Marriage Certificate issued'], faqs: [{q:'Can apply under Special Marriage Act?',a:'Yes, requires 30 days notice period'}] },
  ],

  'a6-tahsildar': [
    { id: 's12a', office_id: 'a6-tahsildar', name: 'Adangal / Pahani Copies', category: 'Land Records', fees: 30, fees_description: '₹30 per copy', eligibility: 'Land owners / Farmers in Kakinada Mandal', processing_time: 'Same day', documents_required: ['Survey Number / Pattadar Passbook Number','Aadhaar Card'], steps: ['Submit request at Revenue counter','Staff pulls digital Webland record','Pay ₹30 fee','Certified certified Adangal copy issued'], faqs: [{q:'Available online?',a:'Yes via Meebhoomi AP portal'}] },
    { id: 's12b', office_id: 'a6-tahsildar', name: 'Pattadar Passbook & Mutation (1B)', category: 'Land Records', fees: 50, fees_description: '₹50 processing fee', eligibility: 'Land buyers / Inheritors', processing_time: '15-30 working days', documents_required: ['Registered Sale Deed / Partition Deed','Old Pattadar Passbook','Applicant Aadhaar & Photo','VRO Verification Report'], steps: ['Submit mutation application with registered deed','VRO & Revenue Inspector field verification','Tahsildar approval in Webland','Digital Pattadar Passbook issued'], faqs: [{q:'Tracking mechanism?',a:'Track status on Meebhoomi website'}] },
    { id: 's12c', office_id: 'a6-tahsildar', name: 'Family Member Certificate', category: 'Certificates', fees: 30, fees_description: '₹30 fee', eligibility: 'Legal heirs of deceased person', processing_time: '7-15 working days', documents_required: ['Death Certificate of Deceased','Aadhaar Cards of all family members','Ration Card Copy','Notarized Affidavit'], steps: ['Submit application form with affidavit','VRO enquiry and neighborhood verification','Tahsildar signs certificate','Collect certified copy'], faqs: [{q:'Used for?',a:'Settling bank accounts, pension, property inheritance'}] },
  ],

  'a7-passport': [
    { id: 's9', office_id: 'a7-passport', name: 'Passport – Fresh', category: 'Passport', fees: 1500, fees_description: 'Normal: ₹1500, Tatkaal: ₹3500', eligibility: 'Indian Citizens', processing_time: '15-30 days (Normal), 3-7 days (Tatkaal)', documents_required: ['Aadhaar Card','DOB Proof (SSC Memo/Birth Cert)','Address Proof','Photos (2)','Signature'], steps: ['Register at passportindia.gov.in','Fill online form & pay fee','Book appointment at PSK Kakinada','Visit PSK with originals for biometric scan','Police verification at local police station','Passport dispatched by Speed Post'], faqs: [{q:'Police verification mandatory?',a:'Yes for normal. Tatkaal: post-dispatch.'},{q:'Can I apply Tatkaal?',a:'Yes for urgent travel with valid proof'}] },
    { id: 's10', office_id: 'a7-passport', name: 'Passport – Renewal', category: 'Passport', fees: 1500, fees_description: 'Normal: ₹1500, Tatkaal: ₹3500', eligibility: 'Holders of expiring/expired passport', processing_time: '15-30 days', documents_required: ['Existing Passport (original)','Aadhaar Card','Address Proof if changed','Photos (2)'], steps: ['Apply at passportindia.gov.in','Upload docs and pay fee','Book appointment at PSK Kakinada','Submit old passport for cancellation','Receive new passport by post'], faqs: [{q:'Address changed?',a:'Submit new address proof like Aadhaar or Bank Passbook'}] },
    { id: 's10b', office_id: 'a7-passport', name: 'Police Clearance Certificate (PCC)', category: 'Passport', fees: 500, fees_description: '₹500 application fee', eligibility: 'Passport holders going abroad for employment/visa', processing_time: '7-14 days', documents_required: ['Valid Indian Passport (original)','Employment / Visa Proof','Address Proof'], steps: ['Apply online on Passport Portal','Book PSK Kakinada appointment','Verification at PSK & local Police Station','PCC certificate issued'], faqs: [{q:'Validity of PCC?',a:'Valid for 6 months'}] },
  ],

  'b1-sbi': [
    { id: 's11', office_id: 'b1-sbi', name: 'Account Opening (Savings/Current)', category: 'Banking', fees: 0, fees_description: 'No opening fee (Min balance ₹500)', eligibility: 'Any Indian resident 18+', processing_time: '1-3 working days', documents_required: ['Aadhaar Card','PAN Card','Passport Photos (2)','Initial Deposit'], steps: ['Visit SBI branch or apply via YONO app','Submit KYC documents & form','Biometric verification at counter','Passbook & Debit card issued'], faqs: [{q:'Can I open online?',a:'Yes via YONO SBI app instantly'},{q:'Minimum balance?',a:'₹500 urban, ₹250 rural'}] },
    { id: 's12', office_id: 'b1-sbi', name: 'Personal & Home Loan Application', category: 'Loans', fees: 0, fees_description: 'Processing fee 0.5% - 1%', eligibility: 'Salaried / Self-employed age 21-65', processing_time: '7-21 working days', documents_required: ['Aadhaar & PAN Card','Income Tax Returns (3 yrs)','Salary Slips (6 months)','Bank Statements (6 months)','Property Title Deeds (for Home Loan)'], steps: ['Meet SBI loan desk officer','Submit loan application & financial documents','Credit appraisal & legal verification','Sanction letter & agreement signing','Loan disbursement'], faqs: [{q:'CIBIL score requirement?',a:'750+ score gets lowest interest rates'}] },
    { id: 's13', office_id: 'b1-sbi', name: 'KYC & Aadhaar Update', category: 'Banking Services', fees: 0, fees_description: 'Free Service', eligibility: 'Existing SBI account holders', processing_time: 'Same day', documents_required: ['Aadhaar Card','PAN Card','Recent Photo'], steps: ['Fill Re-KYC form at branch','Submit copies of Aadhaar & PAN','Biometric authentication at counter','System updated within 24 hours'], faqs: [{q:'How often re-KYC required?',a:'High risk: 2 yrs, Medium: 8 yrs, Low: 10 yrs'}] },
  ],

  'b2-union': [
    { id: 's14a', office_id: 'b2-union', name: 'Savings Account Opening', category: 'Banking', fees: 0, fees_description: 'No opening fee', eligibility: 'Indian Residents', processing_time: '1 working day', documents_required: ['Aadhaar Card','PAN Card','Passport Photos (2)'], steps: ['Fill application form at counter','Submit Aadhaar & PAN copies','Account created & SMS notification sent','Passbook & Cheque book issued'], faqs: [{q:'Is Net Banking included?',a:'Yes, complimentary Internet & Mobile Banking'}] },
    { id: 's14b', office_id: 'b2-union', name: 'Kisan Credit Card (KCC) / Agri Loan', category: 'Loans', fees: 0, fees_description: 'Subsidized Agri Interest Rate (4%)', eligibility: 'Farmers owning agricultural land in East Godavari', processing_time: '7-14 working days', documents_required: ['Land Adangal / Pattadar Passbook','Aadhaar Card','Crop details','Bank Passbook'], steps: ['Submit KCC application form','Agri officer field inspection','Sanction credit limit based on crop area','KCC card issued for cash withdrawal'], faqs: [{q:'Interest subvention available?',a:'3% interest subvention for prompt repayment'}] },
  ],

  'b3-canara': [
    { id: 's15a', office_id: 'b3-canara', name: 'Account Opening & Mobile Banking', category: 'Banking', fees: 0, fees_description: 'Zero balance for Canara Basic Account', eligibility: 'All citizens 18+', processing_time: 'Same day', documents_required: ['Aadhaar Card','PAN Card','Photos (2)'], steps: ['Fill account opening form','Submit original Aadhaar for e-KYC scan','Activate Canara ai1 Mobile Banking app','Debit Card delivered in 7 days'], faqs: [{q:'Is UPI supported?',a:'Yes, supports all UPI apps like PhonePe/GooglePay'}] },
    { id: 's15b', office_id: 'b3-canara', name: 'Gold Loan Application', category: 'Loans', fees: 0, fees_description: 'Low processing fee ₹250', eligibility: 'Gold ornament owners', processing_time: '30 minutes', documents_required: ['Gold Ornaments','Aadhaar Card','PAN Card'], steps: ['Bring gold ornaments to Canara branch','Appraiser tests purity at counter','Loan sanctioned up to 75% of gold value','Cash disbursed or credited to account instantly'], faqs: [{q:'Repayment terms?',a:'Bullet repayment or monthly EMI up to 12 months'}] },
  ],

  'b4-indian': [
    { id: 's16a', office_id: 'b4-indian', name: 'Savings Account & Deposit Services', category: 'Banking', fees: 0, fees_description: 'Free account opening', eligibility: 'Indian citizens', processing_time: '1-2 working days', documents_required: ['Aadhaar Card','PAN Card','Photos (2)'], steps: ['Submit completed form at counter','Pay initial deposit (if applicable)','Collect Passbook','ATM Card mailed within a week'], faqs: [{q:'Senior citizen interest bonus?',a:'0.50% extra interest on Fixed Deposits'}] },
    { id: 's16b', office_id: 'b4-indian', name: 'MSME & Business Loan', category: 'Loans', fees: 0, fees_description: '1% processing fee', eligibility: 'Small business owners & traders', processing_time: '10-15 working days', documents_required: ['GST Registration','PAN & Aadhaar Card','Financial Statements (2 yrs)','Business Property Proof'], steps: ['Submit business plan & GST returns','Bank officer field visit','Sanction under Mudra / MSME scheme','Credit facility opened'], faqs: [{q:'Collateral free loan limit?',a:'Up to ₹10 Lakhs under MUDRA scheme'}] },
  ],

  'b5-andhra': [
    { id: 's17a', office_id: 'b5-andhra', name: 'Account Opening & Pension Credit', category: 'Banking', fees: 0, fees_description: 'Zero balance pension account', eligibility: 'Govt & Private Pensioners', processing_time: '1 working day', documents_required: ['PPO (Pension Payment Order)','Aadhaar Card','PAN Card','Photos (2)'], steps: ['Submit PPO & pension forms','Link Aadhaar for Jeevan Praman digital certificate','Monthly pension credited automatically'], faqs: [{q:'Digital Life Certificate supported?',a:'Yes via doorstep biometric submission'}] },
    { id: 's17b', office_id: 'b5-andhra', name: 'Two-Wheeler & Auto Loan', category: 'Loans', fees: 0, fees_description: '₹500 processing fee', eligibility: 'Salaried & self-employed 21-60', processing_time: '2-4 working days', documents_required: ['Vehicle Quotation from Dealer','Aadhaar & PAN Card','Salary Slip / Income Proof'], steps: ['Submit dealer proforma invoice & income proof','Loan sanctioned up to 85% vehicle cost','DD issued to vehicle dealer','Hypothecation recorded on RC'], faqs: [{q:'Maximum loan tenure?',a:'Up to 5 years (60 months)'}] },
  ],

  'b6-hdfc': [
    { id: 's18a', office_id: 'b6-hdfc', name: 'Savings & Salary Account Opening', category: 'Banking', fees: 0, fees_description: 'Zero balance for salary accounts', eligibility: 'Salaried professionals & Residents', processing_time: 'Instant digital opening', documents_required: ['Aadhaar Card','PAN Card','Company ID (for salary account)','Video KYC'], steps: ['Apply online or at branch counter','Video KYC biometric verification','Instant account number & NetBanking login','Millennia Debit card issued'], faqs: [{q:'Airport lounge access on debit card?',a:'Yes, included on premium debit cards'}] },
    { id: 's18b', office_id: 'b6-hdfc', name: 'Credit Card Application', category: 'Cards', fees: 0, fees_description: 'Lifetime free for select cards', eligibility: 'Monthly income ₹25,000+ or CIBIL 750+', processing_time: '3-7 working days', documents_required: ['PAN Card','Aadhaar Card','Latest 3 months salary slips / ITR'], steps: ['Submit digital application','Income verification & credit check','Card approval & limit assignment','Physical credit card delivered to residential address'], faqs: [{q:'Reward points validity?',a:'Valid for 2 years from earned date'}] },
  ],

  'b7-icici': [
    { id: 's19a', office_id: 'b7-icici', name: 'Account Opening & Wealth Management', category: 'Banking', fees: 0, fees_description: 'Min balance ₹10,000 urban', eligibility: 'Indian Residents & NRIs', processing_time: 'Instant via iMobile app', documents_required: ['Aadhaar Card','PAN Card','Photos (2)'], steps: ['Open instantly via iMobile app or visit branch','Instant e-KYC verification','Set up iMobile Pay & NetBanking','Pick up personalized kit'], faqs: [{q:'NRI account services available?',a:'Yes, NRE/NRO accounts supported'}] },
    { id: 's19b', office_id: 'b7-icici', name: 'Home Loan & Balance Transfer', category: 'Loans', fees: 0, fees_description: 'Processing fee 0.5%', eligibility: 'Salaried / Business owners 21-65', processing_time: '5-10 working days', documents_required: ['PAN & Aadhaar Card','Income proofs (6 months)','Property documents & Approved Plan'], steps: ['Submit online application or visit home loan branch','Property legal valuation check','Sanction letter issued','Disbursement directly to builder/seller'], faqs: [{q:'Prepayment penalty?',a:'Nil penalty on floating rate home loans'}] },
  ],

  'b8-axis': [
    { id: 's20a', office_id: 'b8-axis', name: 'Savings Account Opening', category: 'Banking', fees: 0, fees_description: 'Min balance ₹5,000', eligibility: 'Any resident citizen', processing_time: '1 working day', documents_required: ['Aadhaar Card','PAN Card','Photos (2)'], steps: ['Submit form at Axis Bank branch','Biometric authentication','Open account & download Open by Axis Bank app','Debit card mailed'], faqs: [{q:'Cashback on debit card spends?',a:'1% cashback on online shopping'}] },
    { id: 's20b', office_id: 'b8-axis', name: 'Car Loan & Vehicle Finance', category: 'Loans', fees: 0, fees_description: '₹1,000 processing fee', eligibility: 'Salaried & self-employed 21-65', processing_time: '2-3 working days', documents_required: ['Aadhaar Card','PAN Card','Bank Statement (6 months)','Vehicle Quotation'], steps: ['Select car & get quotation from showroom','Submit loan application & income proof','Spot approval for high CIBIL scores','Disbursement to dealer showroom'], faqs: [{q:'Funding limit?',a:'Up to 100% on-road funding available'}] },
  ],
};

// In-memory queue state per office
const QUEUE_STATE = {};

const getQueueState = (officeId) => {
  const today = new Date().toISOString().split('T')[0];
  if (!QUEUE_STATE[officeId] || QUEUE_STATE[officeId].date !== today) {
    // Simulate some tokens already issued based on time of day
    const hour = new Date().getHours();
    const baseTokens = Math.max(0, (hour - 9) * 8 + Math.floor(Math.random() * 10));
    const currentToken = Math.max(0, baseTokens - Math.floor(Math.random() * 5));
    QUEUE_STATE[officeId] = {
      date: today,
      current_token: currentToken,
      total_tokens_issued: baseTokens,
      is_paused: false,
      status: hour >= 9 && hour <= 17 ? 'active' : 'closed',
      pause_reason: null,
    };
  }
  return QUEUE_STATE[officeId];
};

// Generate realistic hourly analytics
const generateAnalytics = (officeId) => {
  const today = { visitors: 87 + Math.floor(Math.random() * 30), tokensServed: 74, avgWait: 18 + Math.floor(Math.random() * 10) };
  const last7Days = Array.from({ length: 7 }, (_, i) => {
    const d = new Date(); d.setDate(d.getDate() - (6 - i));
    return { date: d.toISOString().split('T')[0], visitors: 40 + Math.floor(Math.random() * 80), avgWait: 10 + Math.floor(Math.random() * 25) };
  });
  const last30Days = Array.from({ length: 30 }, (_, i) => {
    const d = new Date(); d.setDate(d.getDate() - (29 - i));
    return { date: d.toISOString().split('T')[0], visitors: 30 + Math.floor(Math.random() * 100), avgWait: 10 + Math.floor(Math.random() * 30) };
  });
  const peakHours = Array.from({ length: 9 }, (_, i) => {
    const h = i + 9;
    const isPeak = (h >= 10 && h <= 12) || (h >= 14 && h <= 16);
    return { hour: h, label: `${h}:00`, avgVisitors: isPeak ? 25 + Math.floor(Math.random() * 20) : 5 + Math.floor(Math.random() * 12), avgWait: isPeak ? 25 + Math.floor(Math.random() * 15) : 8 + Math.floor(Math.random() * 10) };
  });
  const dayNames = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  const monthly = Array.from({ length: 6 }, (_, i) => {
    const d = new Date(); d.setMonth(d.getMonth() - (5 - i));
    return { month: `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`, visitors: 800 + Math.floor(Math.random() * 600), avgWait: 15 + Math.floor(Math.random() * 20) };
  });
  return { today, last7Days, last30Days, peakHours, busiestDay: { day: 'Monday', avgVisitors: 72 }, fastestDay: { day: 'Saturday', avgVisitors: 28 }, leastCrowdedHour: { hour: 9, avg_visitors: 8 }, monthly };
};

module.exports = { OFFICES, SERVICES, QUEUE_STATE, getQueueState, generateAnalytics };
